# Generated by Django 5.2.7 on 2026-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('status',), name='only_one_published_election'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('max_votes__gte', 1)), name='position_max_votes_at_least_one'),
        ),
    ]
